-- phpMyAdmin SQL Dump
-- version 4.8.4
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Dec 29, 2018 at 06:00 AM
-- Server version: 10.1.37-MariaDB
-- PHP Version: 7.3.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `attendance`
--

-- --------------------------------------------------------

--
-- Table structure for table `employee`
--

CREATE TABLE `employee` (
  `employee_id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `contact` text NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `role` varchar(200) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `employee`
--

INSERT INTO `employee` (`employee_id`, `name`, `contact`, `email`, `password`, `role`) VALUES
(20, 'abc', '9999145153', 'abc@gmail.com', 'abc123', 'admin'),
(25, 'Jyoti Kumari', '9999145153', 'jyoti@gmail.com', 'jyoti123', 'user'),
(26, 'Lipika Sahoo', '999914515', 'lipika@gmail.com', 'lipika123', 'user'),
(33, 'Ravi Kumar', '89374897', 'ravi@gmail.com', 'ravi123', 'user');

-- --------------------------------------------------------

--
-- Table structure for table `employee_attendance`
--

CREATE TABLE `employee_attendance` (
  `id` int(11) NOT NULL,
  `userid` int(11) DEFAULT NULL,
  `month` int(11) DEFAULT NULL,
  `year` int(11) DEFAULT NULL,
  `attendance` text,
  `status` enum('0','1') DEFAULT '1',
  `date_added` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `employee_attendance`
--

INSERT INTO `employee_attendance` (`id`, `userid`, `month`, `year`, `attendance`, `status`, `date_added`, `date_updated`) VALUES
(24, 1, 12, 2018, '[{\"date\":1,\"status\":\"P\"},{\"date\":2,\"status\":\"P\"},{\"date\":3,\"status\":\"P\"},{\"date\":4,\"status\":\"LOP\"},{\"date\":5,\"status\":\"P\"},{\"date\":6,\"status\":\"P\"},{\"date\":7,\"status\":\"LOP\"},{\"date\":8,\"status\":\"P\"},{\"date\":9,\"status\":\"P\"},{\"date\":10,\"status\":\"P\"},{\"date\":11,\"status\":\"P\"},{\"date\":12,\"status\":\"P\"},{\"date\":13,\"status\":\"P\"},{\"date\":14,\"status\":\"P\"},{\"date\":15,\"status\":\"P\"},{\"date\":16,\"status\":\"P\"},{\"date\":17,\"status\":\"P\"},{\"date\":18,\"status\":\"P\"},{\"date\":19,\"status\":\"P\"},{\"date\":20,\"status\":\"P\"},{\"date\":21,\"status\":\"P\"},{\"date\":22,\"status\":\"P\"},{\"date\":23,\"status\":\"P\"},{\"date\":24,\"status\":\"P\"},{\"date\":25,\"status\":\"P\"},{\"date\":26,\"status\":\"P\"},{\"date\":27,\"status\":\"P\"},{\"date\":28,\"status\":\"P\"},{\"date\":29,\"status\":\"P\"},{\"date\":30,\"status\":\"P\"},{\"date\":31,\"status\":\"P\"}]', '1', '2018-12-22 10:36:28', '2018-12-22 10:36:28'),
(25, 4, 12, 2018, '[{\"date\":1,\"status\":\"A\"},{\"date\":2,\"status\":\"\"},{\"date\":3,\"status\":\"A\"},{\"date\":4,\"status\":\"A\"},{\"date\":5,\"status\":\"L\"},{\"date\":6,\"status\":\"A\"},{\"date\":7,\"status\":\"L\"},{\"date\":8,\"status\":\"A\"},{\"date\":9,\"status\":\"\"},{\"date\":10,\"status\":\"A\"},{\"date\":11,\"status\":\"A\"},{\"date\":12,\"status\":\"L\"},{\"date\":13,\"status\":\"A\"},{\"date\":14,\"status\":\"A\"},{\"date\":15,\"status\":\"A\"},{\"date\":16,\"status\":\"\"},{\"date\":17,\"status\":\"A\"},{\"date\":18,\"status\":\"A\"},{\"date\":19,\"status\":\"A\"},{\"date\":20,\"status\":\"A\"},{\"date\":21,\"status\":\"A\"},{\"date\":22,\"status\":\"A\"},{\"date\":23,\"status\":\"\"},{\"date\":24,\"status\":\"A\"},{\"date\":25,\"status\":\"\"},{\"date\":26,\"status\":\"A\"},{\"date\":27,\"status\":\"A\"},{\"date\":28,\"status\":\"A\"},{\"date\":29,\"status\":\"A\"},{\"date\":30,\"status\":\"\"},{\"date\":31,\"status\":\"A\"}]', '1', '2018-12-23 06:26:57', '2018-12-23 06:26:57'),
(26, 2, 12, 2018, '[{\"date\":1,\"status\":\"LOP\"},{\"date\":2,\"status\":\"\"},{\"date\":3,\"status\":\"LOP\"},{\"date\":4,\"status\":\"LOP\"},{\"date\":5,\"status\":\"LOP\"},{\"date\":6,\"status\":\"P\"},{\"date\":7,\"status\":\"LOP\"},{\"date\":8,\"status\":\"P\"},{\"date\":9,\"status\":\"\"},{\"date\":10,\"status\":\"LOP\"},{\"date\":11,\"status\":\"LOP\"},{\"date\":12,\"status\":\"LOP\"},{\"date\":13,\"status\":\"P\"},{\"date\":14,\"status\":\"LOP\"},{\"date\":15,\"status\":\"P\"},{\"date\":16,\"status\":\"\"},{\"date\":17,\"status\":\"LOP\"},{\"date\":18,\"status\":\"LOP\"},{\"date\":19,\"status\":\"LOP\"},{\"date\":20,\"status\":\"LOP\"},{\"date\":21,\"status\":\"LOP\"},{\"date\":22,\"status\":\"LOP\"},{\"date\":23,\"status\":\"\"},{\"date\":24,\"status\":\"LOP\"},{\"date\":25,\"status\":\"\"},{\"date\":26,\"status\":\"LOP\"},{\"date\":27,\"status\":\"LOP\"},{\"date\":28,\"status\":\"LOP\"},{\"date\":29,\"status\":\"LOP\"},{\"date\":30,\"status\":\"\"},{\"date\":31,\"status\":\"LOP\"}]', '1', '2018-12-24 04:19:22', '2018-12-24 04:19:22'),
(27, 5, 12, 2018, '[{\"date\":1,\"status\":\"P\"},{\"date\":2,\"status\":\"P\"},{\"date\":3,\"status\":\"P\"},{\"date\":4,\"status\":\"P\"},{\"date\":5,\"status\":\"P\"},{\"date\":6,\"status\":\"P\"},{\"date\":7,\"status\":\"P\"},{\"date\":8,\"status\":\"P\"},{\"date\":9,\"status\":\"P\"},{\"date\":10,\"status\":\"P\"},{\"date\":11,\"status\":\"P\"},{\"date\":12,\"status\":\"P\"},{\"date\":13,\"status\":\"P\"},{\"date\":14,\"status\":\"P\"},{\"date\":15,\"status\":\"P\"},{\"date\":16,\"status\":\"P\"},{\"date\":17,\"status\":\"P\"},{\"date\":18,\"status\":\"P\"},{\"date\":19,\"status\":\"P\"},{\"date\":20,\"status\":\"P\"},{\"date\":21,\"status\":\"P\"},{\"date\":22,\"status\":\"P\"},{\"date\":23,\"status\":\"P\"},{\"date\":24,\"status\":\"P\"},{\"date\":25,\"status\":\"P\"},{\"date\":26,\"status\":\"P\"},{\"date\":27,\"status\":\"P\"},{\"date\":28,\"status\":\"P\"},{\"date\":29,\"status\":\"P\"},{\"date\":30,\"status\":\"P\"},{\"date\":31,\"status\":\"P\"}]', '1', '2018-12-24 13:23:33', '2018-12-24 13:23:33'),
(28, 7, 12, 2018, '[{\"date\":1,\"status\":\"P\"},{\"date\":2,\"status\":\"P\"},{\"date\":3,\"status\":\"P\"},{\"date\":4,\"status\":\"P\"},{\"date\":5,\"status\":\"L\"},{\"date\":6,\"status\":\"P\"},{\"date\":7,\"status\":\"LOP\"},{\"date\":8,\"status\":\"P\"},{\"date\":9,\"status\":\"P\"},{\"date\":10,\"status\":\"P\"},{\"date\":11,\"status\":\"P\"},{\"date\":12,\"status\":\"P\"},{\"date\":13,\"status\":\"P\"},{\"date\":14,\"status\":\"P\"},{\"date\":15,\"status\":\"P\"},{\"date\":16,\"status\":\"P\"},{\"date\":17,\"status\":\"P\"},{\"date\":18,\"status\":\"P\"},{\"date\":19,\"status\":\"P\"},{\"date\":20,\"status\":\"P\"},{\"date\":21,\"status\":\"P\"},{\"date\":22,\"status\":\"P\"},{\"date\":23,\"status\":\"P\"},{\"date\":24,\"status\":\"P\"},{\"date\":25,\"status\":\"P\"},{\"date\":26,\"status\":\"P\"},{\"date\":27,\"status\":\"P\"},{\"date\":28,\"status\":\"P\"},{\"date\":29,\"status\":\"P\"},{\"date\":30,\"status\":\"P\"},{\"date\":31,\"status\":\"P\"}]', '1', '2018-12-24 13:23:58', '2018-12-24 13:23:58'),
(29, 17, 12, 2018, '[{\"date\":1,\"status\":\"P\"},{\"date\":2,\"status\":\"\"},{\"date\":3,\"status\":\"P\"},{\"date\":4,\"status\":\"P\"},{\"date\":5,\"status\":\"P\"},{\"date\":6,\"status\":\"P\"},{\"date\":7,\"status\":\"P\"},{\"date\":8,\"status\":\"P\"},{\"date\":9,\"status\":\"\"},{\"date\":10,\"status\":\"P\"},{\"date\":11,\"status\":\"P\"},{\"date\":12,\"status\":\"P\"},{\"date\":13,\"status\":\"P\"},{\"date\":14,\"status\":\"P\"},{\"date\":15,\"status\":\"P\"},{\"date\":16,\"status\":\"\"},{\"date\":17,\"status\":\"P\"},{\"date\":18,\"status\":\"P\"},{\"date\":19,\"status\":\"P\"},{\"date\":20,\"status\":\"P\"},{\"date\":21,\"status\":\"P\"},{\"date\":22,\"status\":\"P\"},{\"date\":23,\"status\":\"\"},{\"date\":24,\"status\":\"P\"},{\"date\":25,\"status\":\"\"},{\"date\":26,\"status\":\"\"},{\"date\":27,\"status\":\"\"},{\"date\":28,\"status\":\"\"},{\"date\":29,\"status\":\"\"},{\"date\":30,\"status\":\"\"},{\"date\":31,\"status\":\"\"}]', '1', '2018-12-24 18:19:24', '2018-12-24 18:19:24'),
(30, 16, 12, 2018, '[{\"date\":1,\"status\":\"P\"},{\"date\":2,\"status\":\"P\"},{\"date\":3,\"status\":\"P\"},{\"date\":4,\"status\":\"P\"},{\"date\":5,\"status\":\"P\"},{\"date\":6,\"status\":\"P\"},{\"date\":7,\"status\":\"P\"},{\"date\":8,\"status\":\"LOP\"},{\"date\":9,\"status\":\"P\"},{\"date\":10,\"status\":\"P\"},{\"date\":11,\"status\":\"P\"},{\"date\":12,\"status\":\"P\"},{\"date\":13,\"status\":\"P\"},{\"date\":14,\"status\":\"P\"},{\"date\":15,\"status\":\"P\"},{\"date\":16,\"status\":\"P\"},{\"date\":17,\"status\":\"P\"},{\"date\":18,\"status\":\"P\"},{\"date\":19,\"status\":\"P\"},{\"date\":20,\"status\":\"P\"},{\"date\":21,\"status\":\"P\"},{\"date\":22,\"status\":\"P\"},{\"date\":23,\"status\":\"P\"},{\"date\":24,\"status\":\"P\"},{\"date\":25,\"status\":\"P\"},{\"date\":26,\"status\":\"P\"},{\"date\":27,\"status\":\"P\"},{\"date\":28,\"status\":\"P\"},{\"date\":29,\"status\":\"P\"},{\"date\":30,\"status\":\"P\"},{\"date\":31,\"status\":\"P\"}]', '1', '2018-12-25 05:04:43', '2018-12-25 05:04:43'),
(31, 13, 12, 2018, '[{\"date\":1,\"status\":\"\"},{\"date\":2,\"status\":\"\"},{\"date\":3,\"status\":\"P\"},{\"date\":4,\"status\":\"A\"},{\"date\":5,\"status\":\"\"},{\"date\":6,\"status\":\"\"},{\"date\":7,\"status\":\"\"},{\"date\":8,\"status\":\"\"},{\"date\":9,\"status\":\"\"},{\"date\":10,\"status\":\"\"},{\"date\":11,\"status\":\"\"},{\"date\":12,\"status\":\"\"},{\"date\":13,\"status\":\"\"},{\"date\":14,\"status\":\"\"},{\"date\":15,\"status\":\"\"},{\"date\":16,\"status\":\"\"},{\"date\":17,\"status\":\"\"},{\"date\":18,\"status\":\"\"},{\"date\":19,\"status\":\"\"},{\"date\":20,\"status\":\"\"},{\"date\":21,\"status\":\"\"},{\"date\":22,\"status\":\"\"},{\"date\":23,\"status\":\"\"},{\"date\":24,\"status\":\"\"},{\"date\":25,\"status\":\"\"},{\"date\":26,\"status\":\"\"},{\"date\":27,\"status\":\"\"},{\"date\":28,\"status\":\"\"},{\"date\":29,\"status\":\"\"},{\"date\":30,\"status\":\"\"},{\"date\":31,\"status\":\"\"}]', '1', '2018-12-25 05:10:34', '2018-12-25 05:10:34'),
(32, 18, 12, 2018, '[{\"date\":1,\"status\":\"P\"},{\"date\":2,\"status\":\"P\"},{\"date\":3,\"status\":\"P\"},{\"date\":4,\"status\":\"P\"},{\"date\":5,\"status\":\"P\"},{\"date\":6,\"status\":\"P\"},{\"date\":7,\"status\":\"P\"},{\"date\":8,\"status\":\"P\"},{\"date\":9,\"status\":\"P\"},{\"date\":10,\"status\":\"P\"},{\"date\":11,\"status\":\"P\"},{\"date\":12,\"status\":\"P\"},{\"date\":13,\"status\":\"P\"},{\"date\":14,\"status\":\"P\"},{\"date\":15,\"status\":\"P\"},{\"date\":16,\"status\":\"P\"},{\"date\":17,\"status\":\"P\"},{\"date\":18,\"status\":\"P\"},{\"date\":19,\"status\":\"P\"},{\"date\":20,\"status\":\"P\"},{\"date\":21,\"status\":\"P\"},{\"date\":22,\"status\":\"P\"},{\"date\":23,\"status\":\"P\"},{\"date\":24,\"status\":\"P\"},{\"date\":25,\"status\":\"P\"},{\"date\":26,\"status\":\"P\"},{\"date\":27,\"status\":\"P\"},{\"date\":28,\"status\":\"P\"},{\"date\":29,\"status\":\"P\"},{\"date\":30,\"status\":\"P\"},{\"date\":31,\"status\":\"P\"}]', '1', '2018-12-26 04:45:05', '2018-12-26 04:45:05'),
(33, 21, 12, 2018, '[{\"date\":1,\"status\":\"P\"},{\"date\":2,\"status\":\"P\"},{\"date\":3,\"status\":\"P\"},{\"date\":4,\"status\":\"P\"},{\"date\":5,\"status\":\"\"},{\"date\":6,\"status\":\"P\"},{\"date\":7,\"status\":\"P\"},{\"date\":8,\"status\":\"P\"},{\"date\":9,\"status\":\"P\"},{\"date\":10,\"status\":\"P\"},{\"date\":11,\"status\":\"P\"},{\"date\":12,\"status\":\"P\"},{\"date\":13,\"status\":\"P\"},{\"date\":14,\"status\":\"P\"},{\"date\":15,\"status\":\"P\"},{\"date\":16,\"status\":\"P\"},{\"date\":17,\"status\":\"P\"},{\"date\":18,\"status\":\"P\"},{\"date\":19,\"status\":\"P\"},{\"date\":20,\"status\":\"P\"},{\"date\":21,\"status\":\"P\"},{\"date\":22,\"status\":\"P\"},{\"date\":23,\"status\":\"P\"},{\"date\":24,\"status\":\"P\"},{\"date\":25,\"status\":\"\"},{\"date\":26,\"status\":\"P\"},{\"date\":27,\"status\":\"P\"},{\"date\":28,\"status\":\"P\"},{\"date\":29,\"status\":\"P\"},{\"date\":30,\"status\":\"P\"},{\"date\":31,\"status\":\"P\"}]', '1', '2018-12-26 05:50:44', '2018-12-26 05:50:44'),
(34, 17, 11, 2018, '[{\"date\":1,\"status\":\"L\"},{\"date\":2,\"status\":\"L\"},{\"date\":3,\"status\":\"L\"},{\"date\":4,\"status\":\"\"},{\"date\":5,\"status\":\"L\"},{\"date\":6,\"status\":\"L\"},{\"date\":7,\"status\":\"L\"},{\"date\":8,\"status\":\"L\"},{\"date\":9,\"status\":\"L\"},{\"date\":10,\"status\":\"L\"},{\"date\":11,\"status\":\"\"},{\"date\":12,\"status\":\"L\"},{\"date\":13,\"status\":\"L\"},{\"date\":14,\"status\":\"L\"},{\"date\":15,\"status\":\"L\"},{\"date\":16,\"status\":\"L\"},{\"date\":17,\"status\":\"L\"},{\"date\":18,\"status\":\"\"},{\"date\":19,\"status\":\"L\"},{\"date\":20,\"status\":\"L\"},{\"date\":21,\"status\":\"L\"},{\"date\":22,\"status\":\"L\"},{\"date\":23,\"status\":\"L\"},{\"date\":24,\"status\":\"L\"},{\"date\":25,\"status\":\"\"},{\"date\":26,\"status\":\"L\"},{\"date\":27,\"status\":\"L\"},{\"date\":28,\"status\":\"L\"},{\"date\":29,\"status\":\"L\"},{\"date\":30,\"status\":\"L\"}]', '1', '2018-12-26 08:06:04', '2018-12-26 08:06:04'),
(35, 18, 11, 2018, '[{\"date\":1,\"status\":\"A\"},{\"date\":2,\"status\":\"A\"},{\"date\":3,\"status\":\"A\"},{\"date\":4,\"status\":\"P\"},{\"date\":5,\"status\":\"A\"},{\"date\":6,\"status\":\"A\"},{\"date\":7,\"status\":\"A\"},{\"date\":8,\"status\":\"A\"},{\"date\":9,\"status\":\"A\"},{\"date\":10,\"status\":\"A\"},{\"date\":11,\"status\":\"P\"},{\"date\":12,\"status\":\"A\"},{\"date\":13,\"status\":\"A\"},{\"date\":14,\"status\":\"A\"},{\"date\":15,\"status\":\"A\"},{\"date\":16,\"status\":\"A\"},{\"date\":17,\"status\":\"A\"},{\"date\":18,\"status\":\"P\"},{\"date\":19,\"status\":\"A\"},{\"date\":20,\"status\":\"A\"},{\"date\":21,\"status\":\"A\"},{\"date\":22,\"status\":\"A\"},{\"date\":23,\"status\":\"A\"},{\"date\":24,\"status\":\"A\"},{\"date\":25,\"status\":\"P\"},{\"date\":26,\"status\":\"A\"},{\"date\":27,\"status\":\"A\"},{\"date\":28,\"status\":\"A\"},{\"date\":29,\"status\":\"A\"},{\"date\":30,\"status\":\"A\"}]', '1', '2018-12-26 08:10:18', '2018-12-26 08:10:18'),
(36, 24, 11, 2018, '[{\"date\":1,\"status\":\"\"},{\"date\":2,\"status\":\"\"},{\"date\":3,\"status\":\"\"},{\"date\":4,\"status\":\"\"},{\"date\":5,\"status\":\"\"},{\"date\":6,\"status\":\"\"},{\"date\":7,\"status\":\"\"},{\"date\":8,\"status\":\"\"},{\"date\":9,\"status\":\"\"},{\"date\":10,\"status\":\"\"},{\"date\":11,\"status\":\"\"},{\"date\":12,\"status\":\"P\"},{\"date\":13,\"status\":\"P\"},{\"date\":14,\"status\":\"P\"},{\"date\":15,\"status\":\"P\"},{\"date\":16,\"status\":\"P\"},{\"date\":17,\"status\":\"P\"},{\"date\":18,\"status\":\"\"},{\"date\":19,\"status\":\"P\"},{\"date\":20,\"status\":\"P\"},{\"date\":21,\"status\":\"P\"},{\"date\":22,\"status\":\"P\"},{\"date\":23,\"status\":\"P\"},{\"date\":24,\"status\":\"P\"},{\"date\":25,\"status\":\"\"},{\"date\":26,\"status\":\"P\"},{\"date\":27,\"status\":\"P\"},{\"date\":28,\"status\":\"P\"},{\"date\":29,\"status\":\"P\"},{\"date\":30,\"status\":\"P\"}]', '1', '2018-12-26 09:40:54', '2018-12-26 09:40:54'),
(37, 24, 12, 2018, '[{\"date\":1,\"status\":\"P\"},{\"date\":2,\"status\":\"\"},{\"date\":3,\"status\":\"P\"},{\"date\":4,\"status\":\"P\"},{\"date\":5,\"status\":\"P\"},{\"date\":6,\"status\":\"P\"},{\"date\":7,\"status\":\"P\"},{\"date\":8,\"status\":\"P\"},{\"date\":9,\"status\":\"\"},{\"date\":10,\"status\":\"P\"},{\"date\":11,\"status\":\"P\"},{\"date\":12,\"status\":\"P\"},{\"date\":13,\"status\":\"P\"},{\"date\":14,\"status\":\"P\"},{\"date\":15,\"status\":\"P\"},{\"date\":16,\"status\":\"\"},{\"date\":17,\"status\":\"P\"},{\"date\":18,\"status\":\"P\"},{\"date\":19,\"status\":\"P\"},{\"date\":20,\"status\":\"P\"},{\"date\":21,\"status\":\"P\"},{\"date\":22,\"status\":\"P\"},{\"date\":23,\"status\":\"\"},{\"date\":24,\"status\":\"P\"},{\"date\":25,\"status\":\"\"},{\"date\":26,\"status\":\"P\"},{\"date\":27,\"status\":\"\"},{\"date\":28,\"status\":\"\"},{\"date\":29,\"status\":\"\"},{\"date\":30,\"status\":\"\"},{\"date\":31,\"status\":\"\"}]', '1', '2018-12-26 09:41:24', '2018-12-26 09:41:24'),
(38, 25, 12, 2018, '[{\"date\":1,\"status\":\"LOP\"},{\"date\":2,\"status\":\"P\"},{\"date\":3,\"status\":\"LOP\"},{\"date\":4,\"status\":\"LOP\"},{\"date\":5,\"status\":\"LOP\"},{\"date\":6,\"status\":\"LOP\"},{\"date\":7,\"status\":\"LOP\"},{\"date\":8,\"status\":\"LOP\"},{\"date\":9,\"status\":\"P\"},{\"date\":10,\"status\":\"LOP\"},{\"date\":11,\"status\":\"LOP\"},{\"date\":12,\"status\":\"LOP\"},{\"date\":13,\"status\":\"LOP\"},{\"date\":14,\"status\":\"LOP\"},{\"date\":15,\"status\":\"LOP\"},{\"date\":16,\"status\":\"P\"},{\"date\":17,\"status\":\"LOP\"},{\"date\":18,\"status\":\"LOP\"},{\"date\":19,\"status\":\"LOP\"},{\"date\":20,\"status\":\"LOP\"},{\"date\":21,\"status\":\"LOP\"},{\"date\":22,\"status\":\"LOP\"},{\"date\":23,\"status\":\"P\"},{\"date\":24,\"status\":\"LOP\"},{\"date\":25,\"status\":\"LOP\"},{\"date\":26,\"status\":\"LOP\"},{\"date\":27,\"status\":\"LOP\"},{\"date\":28,\"status\":\"LOP\"},{\"date\":29,\"status\":\"LOP\"},{\"date\":30,\"status\":\"P\"},{\"date\":31,\"status\":\"LOP\"}]', '1', '2018-12-26 09:43:37', '2018-12-26 09:43:37'),
(39, 25, 11, 2018, '[{\"date\":1,\"status\":\"P\"},{\"date\":2,\"status\":\"P\"},{\"date\":3,\"status\":\"P\"},{\"date\":4,\"status\":\"\"},{\"date\":5,\"status\":\"P\"},{\"date\":6,\"status\":\"P\"},{\"date\":7,\"status\":\"P\"},{\"date\":8,\"status\":\"P\"},{\"date\":9,\"status\":\"P\"},{\"date\":10,\"status\":\"P\"},{\"date\":11,\"status\":\"\"},{\"date\":12,\"status\":\"P\"},{\"date\":13,\"status\":\"P\"},{\"date\":14,\"status\":\"P\"},{\"date\":15,\"status\":\"P\"},{\"date\":16,\"status\":\"P\"},{\"date\":17,\"status\":\"P\"},{\"date\":18,\"status\":\"\"},{\"date\":19,\"status\":\"P\"},{\"date\":20,\"status\":\"P\"},{\"date\":21,\"status\":\"P\"},{\"date\":22,\"status\":\"P\"},{\"date\":23,\"status\":\"P\"},{\"date\":24,\"status\":\"P\"},{\"date\":25,\"status\":\"\"},{\"date\":26,\"status\":\"P\"},{\"date\":27,\"status\":\"P\"},{\"date\":28,\"status\":\"P\"},{\"date\":29,\"status\":\"P\"},{\"date\":30,\"status\":\"P\"}]', '1', '2018-12-26 09:44:37', '2018-12-26 09:44:37'),
(40, 25, 1, 2018, '[{\"date\":1,\"status\":\"P\"},{\"date\":2,\"status\":\"P\"},{\"date\":3,\"status\":\"P\"},{\"date\":4,\"status\":\"P\"},{\"date\":5,\"status\":\"P\"},{\"date\":6,\"status\":\"P\"},{\"date\":7,\"status\":\"P\"},{\"date\":8,\"status\":\"P\"},{\"date\":9,\"status\":\"P\"},{\"date\":10,\"status\":\"P\"},{\"date\":11,\"status\":\"P\"},{\"date\":12,\"status\":\"P\"},{\"date\":13,\"status\":\"P\"},{\"date\":14,\"status\":\"P\"},{\"date\":15,\"status\":\"P\"},{\"date\":16,\"status\":\"P\"},{\"date\":17,\"status\":\"P\"},{\"date\":18,\"status\":\"P\"},{\"date\":19,\"status\":\"P\"},{\"date\":20,\"status\":\"P\"},{\"date\":21,\"status\":\"P\"},{\"date\":22,\"status\":\"P\"},{\"date\":23,\"status\":\"P\"},{\"date\":24,\"status\":\"P\"},{\"date\":25,\"status\":\"P\"},{\"date\":26,\"status\":\"P\"},{\"date\":27,\"status\":\"P\"},{\"date\":28,\"status\":\"P\"},{\"date\":29,\"status\":\"P\"},{\"date\":30,\"status\":\"P\"},{\"date\":31,\"status\":\"P\"}]', '1', '2018-12-26 09:53:39', '2018-12-26 09:53:39'),
(41, 25, 2, 2018, '[{\"date\":1,\"status\":\"P\"},{\"date\":2,\"status\":\"P\"},{\"date\":3,\"status\":\"P\"},{\"date\":4,\"status\":\"P\"},{\"date\":5,\"status\":\"P\"},{\"date\":6,\"status\":\"P\"},{\"date\":7,\"status\":\"P\"},{\"date\":8,\"status\":\"P\"},{\"date\":9,\"status\":\"P\"},{\"date\":10,\"status\":\"P\"},{\"date\":11,\"status\":\"P\"},{\"date\":12,\"status\":\"P\"},{\"date\":13,\"status\":\"P\"},{\"date\":14,\"status\":\"P\"},{\"date\":15,\"status\":\"P\"},{\"date\":16,\"status\":\"P\"},{\"date\":17,\"status\":\"P\"},{\"date\":18,\"status\":\"P\"},{\"date\":19,\"status\":\"P\"},{\"date\":20,\"status\":\"P\"},{\"date\":21,\"status\":\"P\"},{\"date\":22,\"status\":\"P\"},{\"date\":23,\"status\":\"P\"},{\"date\":24,\"status\":\"P\"},{\"date\":25,\"status\":\"P\"},{\"date\":26,\"status\":\"P\"},{\"date\":27,\"status\":\"P\"},{\"date\":28,\"status\":\"P\"}]', '1', '2018-12-26 09:54:50', '2018-12-26 09:54:50'),
(42, 27, 12, 2018, '[{\"date\":1,\"status\":\"P\"},{\"date\":2,\"status\":\"P\"},{\"date\":3,\"status\":\"A\"},{\"date\":4,\"status\":\"P\"},{\"date\":5,\"status\":\"A\"},{\"date\":6,\"status\":\"P\"},{\"date\":7,\"status\":\"L\"},{\"date\":8,\"status\":\"P\"},{\"date\":9,\"status\":\"P\"},{\"date\":10,\"status\":\"P\"},{\"date\":11,\"status\":\"P\"},{\"date\":12,\"status\":\"P\"},{\"date\":13,\"status\":\"P\"},{\"date\":14,\"status\":\"P\"},{\"date\":15,\"status\":\"P\"},{\"date\":16,\"status\":\"P\"},{\"date\":17,\"status\":\"P\"},{\"date\":18,\"status\":\"P\"},{\"date\":19,\"status\":\"P\"},{\"date\":20,\"status\":\"P\"},{\"date\":21,\"status\":\"P\"},{\"date\":22,\"status\":\"P\"},{\"date\":23,\"status\":\"P\"},{\"date\":24,\"status\":\"P\"},{\"date\":25,\"status\":\"P\"},{\"date\":26,\"status\":\"P\"},{\"date\":27,\"status\":\"P\"},{\"date\":28,\"status\":\"P\"},{\"date\":29,\"status\":\"P\"},{\"date\":30,\"status\":\"P\"},{\"date\":31,\"status\":\"P\"}]', '1', '2018-12-26 11:28:42', '2018-12-26 11:28:42'),
(43, 23, 12, 2018, '[{\"date\":1,\"status\":\"P\"},{\"date\":2,\"status\":\"P\"},{\"date\":3,\"status\":\"P\"},{\"date\":4,\"status\":\"P\"},{\"date\":5,\"status\":\"A\"},{\"date\":6,\"status\":\"P\"},{\"date\":7,\"status\":\"LOP\"},{\"date\":8,\"status\":\"LOP\"},{\"date\":9,\"status\":\"P\"},{\"date\":10,\"status\":\"P\"},{\"date\":11,\"status\":\"LOP\"},{\"date\":12,\"status\":\"L\"},{\"date\":13,\"status\":\"P\"},{\"date\":14,\"status\":\"P\"},{\"date\":15,\"status\":\"P\"},{\"date\":16,\"status\":\"P\"},{\"date\":17,\"status\":\"P\"},{\"date\":18,\"status\":\"P\"},{\"date\":19,\"status\":\"P\"},{\"date\":20,\"status\":\"P\"},{\"date\":21,\"status\":\"P\"},{\"date\":22,\"status\":\"P\"},{\"date\":23,\"status\":\"P\"},{\"date\":24,\"status\":\"P\"},{\"date\":25,\"status\":\"P\"},{\"date\":26,\"status\":\"P\"},{\"date\":27,\"status\":\"P\"},{\"date\":28,\"status\":\"P\"},{\"date\":29,\"status\":\"P\"},{\"date\":30,\"status\":\"P\"},{\"date\":31,\"status\":\"P\"}]', '1', '2018-12-26 12:48:42', '2018-12-26 12:48:42'),
(44, 26, 12, 2018, '[{\"date\":1,\"status\":\"P\"},{\"date\":2,\"status\":\"P\"},{\"date\":3,\"status\":\"P\"},{\"date\":4,\"status\":\"P\"},{\"date\":5,\"status\":\"P\"},{\"date\":6,\"status\":\"A\"},{\"date\":7,\"status\":\"P\"},{\"date\":8,\"status\":\"P\"},{\"date\":9,\"status\":\"P\"},{\"date\":10,\"status\":\"P\"},{\"date\":11,\"status\":\"P\"},{\"date\":12,\"status\":\"P\"},{\"date\":13,\"status\":\"L\"},{\"date\":14,\"status\":\"P\"},{\"date\":15,\"status\":\"P\"},{\"date\":16,\"status\":\"P\"},{\"date\":17,\"status\":\"P\"},{\"date\":18,\"status\":\"P\"},{\"date\":19,\"status\":\"P\"},{\"date\":20,\"status\":\"P\"},{\"date\":21,\"status\":\"P\"},{\"date\":22,\"status\":\"P\"},{\"date\":23,\"status\":\"P\"},{\"date\":24,\"status\":\"P\"},{\"date\":25,\"status\":\"P\"},{\"date\":26,\"status\":\"P\"},{\"date\":27,\"status\":\"P\"},{\"date\":28,\"status\":\"P\"},{\"date\":29,\"status\":\"P\"},{\"date\":30,\"status\":\"P\"},{\"date\":31,\"status\":\"P\"}]', '1', '2018-12-27 06:17:35', '2018-12-27 06:17:35'),
(45, 29, 12, 2018, '[{\"date\":1,\"status\":\"P\"},{\"date\":2,\"status\":\"\"},{\"date\":3,\"status\":\"P\"},{\"date\":4,\"status\":\"P\"},{\"date\":5,\"status\":\"A\"},{\"date\":6,\"status\":\"P\"},{\"date\":7,\"status\":\"P\"},{\"date\":8,\"status\":\"P\"},{\"date\":9,\"status\":\"\"},{\"date\":10,\"status\":\"P\"},{\"date\":11,\"status\":\"P\"},{\"date\":12,\"status\":\"A\"},{\"date\":13,\"status\":\"P\"},{\"date\":14,\"status\":\"P\"},{\"date\":15,\"status\":\"P\"},{\"date\":16,\"status\":\"\"},{\"date\":17,\"status\":\"P\"},{\"date\":18,\"status\":\"P\"},{\"date\":19,\"status\":\"P\"},{\"date\":20,\"status\":\"P\"},{\"date\":21,\"status\":\"P\"},{\"date\":22,\"status\":\"P\"},{\"date\":23,\"status\":\"\"},{\"date\":24,\"status\":\"P\"},{\"date\":25,\"status\":\"L\"},{\"date\":26,\"status\":\"P\"},{\"date\":27,\"status\":\"A\"},{\"date\":28,\"status\":\"P\"},{\"date\":29,\"status\":\"P\"},{\"date\":30,\"status\":\"\"},{\"date\":31,\"status\":\"P\"}]', '1', '2018-12-27 06:22:51', '2018-12-27 06:22:51'),
(46, 33, 12, 2018, '[{\"date\":1,\"status\":\"P\"},{\"date\":2,\"status\":\"P\"},{\"date\":3,\"status\":\"P\"},{\"date\":4,\"status\":\"A\"},{\"date\":5,\"status\":\"P\"},{\"date\":6,\"status\":\"P\"},{\"date\":7,\"status\":\"P\"},{\"date\":8,\"status\":\"P\"},{\"date\":9,\"status\":\"P\"},{\"date\":10,\"status\":\"P\"},{\"date\":11,\"status\":\"P\"},{\"date\":12,\"status\":\"P\"},{\"date\":13,\"status\":\"P\"},{\"date\":14,\"status\":\"P\"},{\"date\":15,\"status\":\"P\"},{\"date\":16,\"status\":\"P\"},{\"date\":17,\"status\":\"P\"},{\"date\":18,\"status\":\"P\"},{\"date\":19,\"status\":\"P\"},{\"date\":20,\"status\":\"P\"},{\"date\":21,\"status\":\"P\"},{\"date\":22,\"status\":\"P\"},{\"date\":23,\"status\":\"P\"},{\"date\":24,\"status\":\"P\"},{\"date\":25,\"status\":\"P\"},{\"date\":26,\"status\":\"P\"},{\"date\":27,\"status\":\"P\"},{\"date\":28,\"status\":\"P\"},{\"date\":29,\"status\":\"P\"},{\"date\":30,\"status\":\"P\"},{\"date\":31,\"status\":\"P\"}]', '1', '2018-12-27 07:26:46', '2018-12-27 07:26:46'),
(47, 73, 12, 2018, '[{\"date\":1,\"status\":\"P\"},{\"date\":2,\"status\":\"P\"},{\"date\":3,\"status\":\"P\"},{\"date\":4,\"status\":\"P\"},{\"date\":5,\"status\":\"P\"},{\"date\":6,\"status\":\"P\"},{\"date\":7,\"status\":\"P\"},{\"date\":8,\"status\":\"P\"},{\"date\":9,\"status\":\"P\"},{\"date\":10,\"status\":\"P\"},{\"date\":11,\"status\":\"P\"},{\"date\":12,\"status\":\"P\"},{\"date\":13,\"status\":\"P\"},{\"date\":14,\"status\":\"P\"},{\"date\":15,\"status\":\"P\"},{\"date\":16,\"status\":\"P\"},{\"date\":17,\"status\":\"P\"},{\"date\":18,\"status\":\"P\"},{\"date\":19,\"status\":\"P\"},{\"date\":20,\"status\":\"P\"},{\"date\":21,\"status\":\"P\"},{\"date\":22,\"status\":\"P\"},{\"date\":23,\"status\":\"P\"},{\"date\":24,\"status\":\"P\"},{\"date\":25,\"status\":\"P\"},{\"date\":26,\"status\":\"P\"},{\"date\":27,\"status\":\"P\"},{\"date\":28,\"status\":\"P\"},{\"date\":29,\"status\":\"P\"},{\"date\":30,\"status\":\"P\"},{\"date\":31,\"status\":\"P\"}]', '1', '2018-12-28 13:55:25', '2018-12-28 13:55:25');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `employee`
--
ALTER TABLE `employee`
  ADD PRIMARY KEY (`employee_id`,`email`,`password`),
  ADD UNIQUE KEY `employee_id` (`employee_id`);

--
-- Indexes for table `employee_attendance`
--
ALTER TABLE `employee_attendance`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `employee`
--
ALTER TABLE `employee`
  MODIFY `employee_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=75;

--
-- AUTO_INCREMENT for table `employee_attendance`
--
ALTER TABLE `employee_attendance`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=48;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
